CREATE DATABASE galpao_bosch;

USE galpao_bosch;

CREATE TABLE GALPAO(
	ID bigint(7) PRIMARY KEY AUTO_INCREMENT,
	PRODUTO varchar(30),
    QUANTIDADE int
    );
    
DESCRIBE GALPAO;

SELECT * FROM GALPAO;

INSERT INTO GALPAO(produto,quantidade) VALUES('MARTELETE','3');

SELECT * FROM GALPAO WHERE PRODUTO = 'FURADEIRA';

ALTER TABLE GALPAO 
	ADD  DATA_ date;
    
ALTER TABLE GALPAO 
	ADD  HORA_ time;

UPDATE GALPAO SET DATA_ = '2020-12-27', HORA_ = '22:40:37' WHERE ID = 9
